npx vercel env add JWT_SECRET production --value sc-jwt-prod-7f3a9b2c8d4e1f6a0b5c3d9e8f7a2b4c6d1e3f5a9b0c2d4e --yes
npx vercel env add STRIPE_SECRET_KEY production --value sk_test_placeholder --yes
npx vercel env add VITE_STRIPE_PUBLIC_KEY production --value pk_test_placeholder --yes
npx vercel env add GEMINI_API_KEY production --value AIzaSyAssQGmMLc4zbC74kXZs8Gw17Axg3h58D0 --yes
npx vercel env add PUSHER_APP_ID production --value 2133859 --yes
npx vercel env add PUSHER_KEY production --value 9077bd9b5f7c68a64684 --yes
npx vercel env add PUSHER_SECRET production --value 8c549065e5ff2f9c8855 --yes
npx vercel env add PUSHER_CLUSTER production --value eu --yes
npx vercel env add VITE_PUSHER_KEY production --value 29633946efcf446e1634 --yes
npx vercel env add VITE_PUSHER_CLUSTER production --value mt1 --yes
npx vercel env add NODE_ENV production --value production --yes
npx vercel env add APP_URL production --value https://service-connect-nu.vercel.app --yes
